# services:
#   db:
#     image: pgvector/pgvector:pg16
#     container_name: rag_pgvector_db
#     environment:
#       POSTGRES_USER: rag
#       POSTGRES_PASSWORD: rag
#       POSTGRES_DB: rag_kb
#     ports:
#       - "5432:5432"
#     volumes:
#       - rag_pgdata:/var/lib/postgresql/data
#       - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

# volumes:
#   rag_pgdata:

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: rag_pgvector_db
    environment:
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: ragpass
      POSTGRES_DB: rag_kb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    # IMPORTANT: don't expose db publicly on a server
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rag -d rag_kb"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg://rag:ragpass@db:5432/rag_kb
      JWT_SECRET: "change-me-in-prod"
      OLLAMA_URL: "http://ollama:11434"
      OLLAMA_MODEL: "llama3.1:8b"
      OLLAMA_TIMEOUT_S: "90"
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"
    ports: 
      - "8000:8000"
    volumes:
      - ../../data:/app/data  # so uploads/docs persist

  web:
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile
    environment:
      API_URL: http://api:8000
    depends_on:
      - api
    ports:
      - "8501:8501"

  ollama:
      image: ollama/ollama:latest
      container_name: rag_ollama
      volumes:
        - ollama:/root/.ollama
      expose:
        - "11434"
      # Optional: if you want to pull models from your host for testing:
      # ports:
      #   - "11434:11434"
  

volumes:
  pgdata:
  ollama: